
version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 138806120984.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=138806120984.dkr.ecr.us-east-1.amazonaws.com/frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo IMAGE_TAG=$IMAGE_TAG >> output-data.txt
      - echo REPO_NAME=frontend >> output-data.txt
artifacts:
  files:
    - './output-data.txt'
  discard-paths: yes